# Base
FROM node:latest as base
# in this case, Red Hat's ubi8 s2i images use dnf, which must be run as root
USER root
RUN apt update -y && apt upgrade -y

# Create app directory
WORKDIR /app

FROM base AS dev

COPY . .

RUN npm install

EXPOSE 3000

CMD ["npm", "run", "start:dev"]
