services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    environment:
      PORT: ${PORT:-3001}
      FRONTEND_URL: $(FRONTEND_URL:-http://localhost:3000)
      DATABASE_URL: ${DATABASE_URL:-postgresql://distanceApiDatabaseUser:superSecretDistanceApiDatabasePassword@database/distanceApiDatabaseName}
      NODE_ENV: ${NODE_ENV:-development}
      NAME: ${NAME:-distance-api}
      DISTANCE_API_URL: ${DISTANCE_API_URL:-http://router.project-osrm.org}
      COORDINATES_API_URL: ${COORDINATES_API_URL:-https://nominatim.openstreetmap.org}
      COORDINATE_SERVICE_SLEEP_TIME_MS: ${COORDINATE_SERVICE_SLEEP_TIME_MS:-5000}
    ports:
      - 5734:3001
    volumes:
      - .:/app
    networks:
      - database
    depends_on:
      - database
  database:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-distanceApiDatabaseUser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-superSecretDistanceApiDatabasePassword}
      POSTGRES_DB: ${POSTGRES_DB:-distanceApiDatabaseName}
    networks:
      - database
    volumes:
      - postgres_storage:/var/lib/postgresql/data

networks:
  database:
volumes:
  postgres_storage: {}